library(tidyverse)
library(shiny)
library(tibble)


aj_raw <- read.csv('https://raw.githubusercontent.com/acRnR/Referential-Choice-in-Subordinate-Clauses-in-Native-and-L2-Russian-Speakers/master/data/acceptabilityjudgement.csv')
aj_stim <- read.csv('https://raw.githubusercontent.com/acRnR/Referential-Choice-in-Subordinate-Clauses-in-Native-and-L2-Russian-Speakers/master/data/aj_stimuli.csv')
aj_t <- t(aj_raw)

aj_fin <- cbind(aj_stim, aj_t)
rownames(aj_fin) <- c()
aj_zscore <- aj_fin

aj_zscore$`1` <- scale(aj_fin$`1`, center = TRUE, scale = TRUE)
aj_zscore$`2` <- scale(aj_fin$`2`, center = TRUE, scale = TRUE)
aj_zscore$`3` <- scale(aj_fin$`3`, center = TRUE, scale = TRUE)
aj_zscore$`4` <- scale(aj_fin$`4`, center = TRUE, scale = TRUE)
aj_zscore$`5` <- scale(aj_fin$`5`, center = TRUE, scale = TRUE)
aj_zscore$`6` <- scale(aj_fin$`6`, center = TRUE, scale = TRUE)
aj_zscore$`7` <- scale(aj_fin$`7`, center = TRUE, scale = TRUE)
aj_zscore$`8` <- scale(aj_fin$`8`, center = TRUE, scale = TRUE)
aj_zscore$`9` <- scale(aj_fin$`9`, center = TRUE, scale = TRUE)
aj_zscore$`10` <- scale(aj_fin$`10`, center = TRUE, scale = TRUE)
aj_zscore$`11` <- scale(aj_fin$`11`, center = TRUE, scale = TRUE)
aj_zscore$`12` <- scale(aj_fin$`12`, center = TRUE, scale = TRUE)
aj_zscore$`13` <- scale(aj_fin$`13`, center = TRUE, scale = TRUE)
aj_zscore$`14` <- scale(aj_fin$`14`, center = TRUE, scale = TRUE)
aj_zscore$`15` <- scale(aj_fin$`15`, center = TRUE, scale = TRUE)
aj_zscore$`16` <- scale(aj_fin$`16`, center = TRUE, scale = TRUE)
aj_zscore$`17` <- scale(aj_fin$`17`, center = TRUE, scale = TRUE)
aj_zscore$`18` <- scale(aj_fin$`18`, center = TRUE, scale = TRUE)
aj_zscore$`19` <- scale(aj_fin$`19`, center = TRUE, scale = TRUE)
aj_zscore$`20` <- scale(aj_fin$`20`, center = TRUE, scale = TRUE)
aj_zscore$`21` <- scale(aj_fin$`21`, center = TRUE, scale = TRUE)
aj_zscore$`22` <- scale(aj_fin$`22`, center = TRUE, scale = TRUE)
aj_zscore$`23` <- scale(aj_fin$`23`, center = TRUE, scale = TRUE)
aj_zscore$`24` <- scale(aj_fin$`24`, center = TRUE, scale = TRUE)
aj_zscore$`25` <- scale(aj_fin$`25`, center = TRUE, scale = TRUE)
aj_zscore$`26` <- scale(aj_fin$`26`, center = TRUE, scale = TRUE)
aj_zscore$`27` <- scale(aj_fin$`27`, center = TRUE, scale = TRUE)
aj_zscore$`28` <- scale(aj_fin$`28`, center = TRUE, scale = TRUE)

install.packages('xlsReadWrite')

write.csv(aj_zscore, file = "ajzscore.csv")
